language: node_js
node_js:
  - "7.2.0"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8
before_script:
  - npm run-script build
script:
  - npm test
